name: distributions
description: "Fisher F-distribution. Student's t distribution"
version: 0.0.3
homepage: https://github.com/shebnik/distributions

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: DistributionsPluginCApi
      web:
        fileName: distributions_web.dart
        pluginClass: DistributionsWeb